loglevel = 5
workspace = "/home/dj/workspace/github.com/nezha/nezha-chat-backend"
root_package_slash = 3

#mysql 参数配置
[mysql]
debug = true
# 连接地址
host = "182.61.3.243"
# 连接端口
port= 3306
# 用户名
user = "test"
# 密码
password = "888"
# 数据库
db_name = "nezha_chat_user"
# 连接参数
parameters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

[rabbitmq]
user = "guest"
password = "guest"
host = "127.0.0.1"
port = 5672

[etcd]
addrs = ["etcd:2379"]
register_ttl = 15
register_interval = 10



[micro]
name = "nezha.chat.user.srv.service"
version = "1"